version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    # Expose the dynamic port range for P2P file sharing
    expose:
      - "49152-65535:49152-65535"
    # For production, you might want to add port mappings for the dynamic ports
    # ports:
    #   - "49152-65535:49152-65535"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
